### Регистрация нового пользователя (только для админов)
POST http://localhost:8080/admin/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6ImF6YW1hdCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc0NDM1MTIyMCwiaWF0IjoxNzQ0MzUwMzIwfQ.QH7t17rvFjALTNhP0Eg4SxEHgTLiwRtHiOQQ42-2VZs

{
  "username": "JGquintel",
  "password": "123",
  "email": "JG@gmail.com",
  "role": "user"
}

### Вход пользователя
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "azamat",
  "password": "123"
}

### Обновление токена
POST http://localhost:8080/refresh
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6ImF6YW1hdCIsInJvbGUiOiJhZG1pbiIsImp0aSI6IjRHbm1xQWhfYVZUdFRicHpBZ2JId2c9PSIsImV4cCI6MTc0NTIxNTQ4OSwiaWF0IjoxNzQ0NjEwNjg5fQ.Fo6d17bgu2-cfdI8LZNBgcVc-b_uoFyC-NlTqpLX194"
}